In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import AgglomerativeClustering
from sklearn.datasets import load_digits

## Agglomerative Clustering on Digits dataset

In [2]:
digits = load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

### 2 Clusters

In [3]:
digits_agg = AgglomerativeClustering().fit(digits.data)
digits_agg

AgglomerativeClustering()

In [4]:
digits_agg.labels_

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [5]:
digits_agg.n_leaves_

1797

### 3 Clusters

In [6]:
digits_agg3 = AgglomerativeClustering(n_clusters = 3).fit(digits.data)
digits_agg3

AgglomerativeClustering(n_clusters=3)

In [7]:
digits_agg3.labels_

array([0, 2, 2, ..., 2, 1, 2], dtype=int64)

### 7 clusters

In [10]:
digits_agg7 = AgglomerativeClustering(n_clusters = 7).fit(digits.data)
digits_agg7

AgglomerativeClustering(n_clusters=7)

In [11]:
digits_agg7.labels_

array([3, 0, 0, ..., 0, 4, 0], dtype=int64)

### 10 Clusters

In [12]:
digits_agg10 = AgglomerativeClustering(n_clusters = 10).fit(digits.data)
digits_agg10

AgglomerativeClustering(n_clusters=10)

In [13]:
digits_agg10.labels_

array([7, 9, 4, ..., 4, 1, 4], dtype=int64)