In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Midterm 1

## Question 1

### part 1

In [9]:
arr = np.arange(2,21,2).reshape(5,2)
arr

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

#### a.

In [10]:
arr_multiplied = arr * 3
arr_multiplied

array([[ 6, 12],
       [18, 24],
       [30, 36],
       [42, 48],
       [54, 60]])

#### b.

In [11]:
np.sum(arr_multiplied)

330

#### c.

In [12]:
arr ** 3

array([[   8,   64],
       [ 216,  512],
       [1000, 1728],
       [2744, 4096],
       [5832, 8000]])

### part 2

In [16]:
A = np.arange(1,6)
B = np.arange(6,11)

In [19]:
A

array([1, 2, 3, 4, 5])

In [20]:
B

array([ 6,  7,  8,  9, 10])

#### a.

In [17]:
A + B

array([ 7,  9, 11, 13, 15])

In [18]:
A - B

array([-5, -5, -5, -5, -5])

In [21]:
A * B

array([ 6, 14, 24, 36, 50])

In [22]:
A / B

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

#### b.

In [25]:
A_sqr = A ** 2
B_sqr = B ** 2
A_sqr + B_sqr

array([ 37,  53,  73,  97, 125])

#### c.

In [28]:
A.dot(B)

130

## Question 2

### part 1

In [30]:
temperatures_dict = {'Maxine' : [41,55,47], 'James' : [44, 59, 42], 'Amanda' : [40, 60, 44]}
temperatures = pd.DataFrame(temperatures_dict)
temperatures

Maxine  James  Amanda
0      41     44      40
1      55     59      60
2      47     42      44

### part 2

In [31]:
temperatures = pd.DataFrame(temperatures_dict, index = ['Morning', 'Afternoon', 'Evening'])
temperatures

Maxine  James  Amanda
Morning        41     44      40
Afternoon      55     59      60
Evening        47     42      44

### part 3

In [32]:
temperatures.Maxine

Morning      41
Afternoon    55
Evening      47
Name: Maxine, dtype: int64

### part 4

In [34]:
temperatures.loc['Morning']

Maxine    41
James     44
Amanda    40
Name: Morning, dtype: int64

### part 5

In [35]:
temperatures.loc[['Morning', 'Evening']]

Maxine  James  Amanda
Morning      41     44      40
Evening      47     42      44

### part 6

In [42]:
temperatures[['Amanda','Maxine']]

Amanda  Maxine
Morning        40      41
Afternoon      60      55
Evening        44      47

### part 7

In [48]:
temperatures.iloc[[0,2], [2,0]]

Amanda  Maxine
Morning      40      41
Evening      44      47

### part 8

In [49]:
temperatures.describe()

Maxine      James     Amanda
count   3.000000   3.000000   3.000000
mean   47.666667  48.333333  48.000000
std     7.023769   9.291573  10.583005
min    41.000000  42.000000  40.000000
25%    44.000000  43.000000  42.000000
50%    47.000000  44.000000  44.000000
75%    51.000000  51.500000  52.000000
max    55.000000  59.000000  60.000000

### part 9

In [50]:
temperatures.transpose()

Morning  Afternoon  Evening
Maxine       41         55       47
James        44         59       42
Amanda       40         60       44

### part 10

In [51]:
temperatures.sort_index(axis = 1)

Amanda  James  Maxine
Morning        40     44      41
Afternoon      60     59      55
Evening        44     42      47