## Numpy again

In [1]:
import numpy as np


In [2]:
names = np.array(['Janet', 'Bob', 'John', 'Kate'])
names

array(['Janet', 'Bob', 'John', 'Kate'], dtype='<U5')

In [3]:
names == 'Bob'

array([False,  True, False, False])

In [4]:
names != 'Bob'

array([ True, False,  True,  True])

In [5]:
names[names != 'Bob']

array(['Janet', 'John', 'Kate'], dtype='<U5')

In [6]:
names[names != 'Bob'] = 'Joe'

In [7]:
names

array(['Joe', 'Bob', 'Joe', 'Joe'], dtype='<U5')

In [8]:
np.unique(names)

array(['Bob', 'Joe'], dtype='<U5')

### arithmetic operations on Arrays

In [9]:
nums = np.arange(5)
nums

array([0, 1, 2, 3, 4])

In [10]:
np.sqrt(nums)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [11]:
nums + 1

array([1, 2, 3, 4, 5])

In [12]:
nums * 10

array([ 0, 10, 20, 30, 40])

In [13]:
nums ** 3

array([ 0,  1,  8, 27, 64])

In [14]:
x = np.ones(5) + 2
x

array([3., 3., 3., 3., 3.])

In [15]:
x - nums 

array([ 3.,  2.,  1.,  0., -1.])

In [16]:
nums

array([0, 1, 2, 3, 4])

In [17]:
x * nums

array([ 0.,  3.,  6.,  9., 12.])

In [19]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
c * c #element wise multiplication

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
c.dot(c) # matrix multiplication

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [22]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

In [23]:
a == b

array([False,  True, False,  True])

In [24]:
a > b

array([False, False,  True, False])

In [25]:
a <= b

array([ True,  True, False,  True])

In [26]:
c = np.array([4,2,2,4])
c

array([4, 2, 2, 4])

In [27]:
a

array([1, 2, 3, 4])

In [28]:
b

array([4, 2, 2, 4])

In [29]:
np.array_equal(a,b)

False

In [31]:
np.array_equal(b,c)

True

In [32]:
x = np.array([10,20,30,40,50])
np.sum(x)

150

In [33]:
x.sum()

150

In [34]:
x.argmax()

4

In [35]:
x.argmin()

0

In [36]:
x.max()

50

In [37]:
x.min()

10

In [38]:
x = np.array([[1,1], [2,2]])
x

array([[1, 1],
       [2, 2]])

In [39]:
x.sum()

6

In [40]:
x.sum(axis=0)

array([3, 3])

In [41]:
x.sum(axis=1)

array([2, 4])

In [42]:
x[0,:].sum() 

2

In [43]:
x[1,:].sum()

4

In [44]:
x[:,1].sum()

3

## Broadcasting

In [45]:
a = np.array([[0,0,0], [10,10,10], [20,20,20], [30,30,30]])
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [46]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [47]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [48]:
c = np.array([[0], [1], [2], [3]])
c

array([[0],
       [1],
       [2],
       [3]])

In [49]:
a + c

array([[ 0,  0,  0],
       [11, 11, 11],
       [22, 22, 22],
       [33, 33, 33]])

In [50]:
c + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

### Example 1

In [55]:
arr = np.arange(2,41,2).reshape(4,5)
arr

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

### Example 2

In [56]:
grades = np.array([[87,96,70], [100,87,90], [94,77,90], [100,81,82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [57]:
grades.min()

70

In [58]:
grades.max()

100

In [59]:
grades.sum()

1054

In [63]:
grades.sum() / 12

87.83333333333333

In [83]:
grades.max(axis = 1)

array([ 96, 100,  94, 100])

In [84]:
grades.min(axis = 1)

array([70, 87, 77, 81])

In [85]:
grades.sum(axis = 1) / 3

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [66]:
grades[0,:].min()

70

In [67]:
grades[0,:].max()

96

In [74]:
grades[0,:].sum()

253

In [75]:
grades[0,:].sum() / 3

84.33333333333333

In [68]:
grades[1,:].min()

87

In [69]:
grades[1,:].max()

100

In [76]:
grades[1,:].sum()

277

In [77]:
grades[1,:].sum() / 3

92.33333333333333

In [70]:
grades[2,:].min()

77

In [71]:
grades[2,:].max()

94

In [78]:
grades[2,:].sum()

261

In [79]:
grades[2,:].sum() / 3

87.0

In [72]:
grades[3,:].min()

81

In [73]:
grades[3,:].max()

100

In [80]:
grades[3,:].sum()

263

In [82]:
grades[3,:].sum() / 3

87.66666666666667

### example 3

In [86]:
array = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
# or could be numbers = np.arange(1,16).reshape(3,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [87]:
array_sel = array[1,:]
array_sel

array([ 6,  7,  8,  9, 10])

In [90]:
array_sel2 = array[::2,:]
array_sel2

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [91]:
array_sel3 = array[:,1:4]
array_sel3

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

## List comprehension:

In [92]:
[x for x in range(5)]

[0, 1, 2, 3, 4]

In [93]:
lst = []
for x in range(5):
    lst.append(x)

In [94]:
lst

[0, 1, 2, 3, 4]

lst and x lists are equal, but just two different ways of creating them

In [95]:
lst = []
for x in range(5):
    if x % 2 == 0:
        lst.append(x)

In [96]:
lst

[0, 2, 4]

In [97]:
lst1 = [x for x in range(5) if x%2 == 0]
lst1

[0, 2, 4]

In [98]:
squares = [x * x for x in range(5)]
squares

[0, 1, 4, 9, 16]

In [99]:
even_numbers = [2,4,6,8,10]
even_squares = [x * x for x in even_numbers]
even_squares

[4, 16, 36, 64, 100]

## dictionary comprehension

In [100]:
square_dict = {x:x * x for x in range(5)}
square_dict

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [101]:
pairs = [(x,y) for x in range(10) for y in range(10)]
pairs

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (3, 9),
 (4, 0),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8),
 (4, 9),
 (5, 0),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (5, 7),
 (5, 8),
 (5, 9),
 (6, 0),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6),
 (6, 7),
 (6, 8),
 (6, 9),
 (7, 0),
 (7, 1),
 (7, 2),
 (7, 3),
 (7, 4),
 (7, 5),
 (7, 6),
 (7, 7),
 (7, 8),
 (7, 9),
 (8, 0),
 (8, 1),
 (8, 2),
 (8, 3),
 (8, 4),
 (8, 5),
 (8, 6),
 (8, 7),
 (8, 8),
 (8, 9),
 (9, 0),
 (9, 1),
 (9, 2),
 (9, 3),
 (9, 4),
 (9, 5),
 (9, 6),
 (9, 7),
 (9, 8),
 (9, 9)]