## Numpy

In [1]:
import numpy as np
num_list = [11,22,33,44,55]
num_list

[11, 22, 33, 44, 55]

In [2]:
num_array = np.array(num_list)
num_array

array([11, 22, 33, 44, 55])

In [3]:
num_list2 = [[11,22,33,44,55], [66,77,88,99,100]]
num_list2

[[11, 22, 33, 44, 55], [66, 77, 88, 99, 100]]

In [4]:
num_array2 = np.array(num_list2)
num_array2

array([[ 11,  22,  33,  44,  55],
       [ 66,  77,  88,  99, 100]])

In [5]:
num_list3 = [list(range(10)), list(range(10,20)), list(range(20,30))]
num_list3

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]

In [6]:
num_array3 = np.array(num_list3)
num_array3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [7]:
# go back from an array to a list by using .tolist()
num_array3.tolist()

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]

In [8]:
#generate array of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [12]:
# Create elements of arrays that are spaced equally between two values in linear space
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [14]:
#create numbers spaced equally between two values in log space
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

In [15]:
np.logspace(0,3,10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [16]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [17]:
np.arange(4,20,2)

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.arange(6, dtype=float)

array([0., 1., 2., 3., 4., 5.])

In [19]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
arr1 = np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
arr1.dtype

dtype('int64')

In [23]:
arr1.shape

(4, 5)

In [24]:
arr1.size

20

In [25]:
len(arr1)

4

In [26]:
# this method is applied on a copy of the array and does NOT modify the original array
arr1.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [27]:
# this method is applied on a copy of the array and does NOT modify the original array
arr1.transpose()

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [28]:
arr2 = arr1.reshape(2,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [29]:
arr1.transpose()

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [30]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
arr3 = arr1.transpose()
arr3

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [32]:
# .flatter() makes the array back into 1 row, and does NOT modify the original array
arr1.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
array1 = np.array([0,1])
array1

array([0, 1])

In [35]:
array2 = np.array([2,3])
array2

array([2, 3])

In [36]:
array3 = np.stack((array1, array2), axis = 0)
array3

array([[0, 1],
       [2, 3]])

In [37]:
array4 = np.stack((array1, array2), axis = 1)
array4

array([[0, 2],
       [1, 3]])

get access to array elements

In [38]:
arr = np.arange(20, dtype = float).reshape(5,4)
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [40]:
arr[0]

array([0., 1., 2., 3.])

In [41]:
arr[1]

array([4., 5., 6., 7.])

In [42]:
for i in range(len(arr)):
    print(arr[i])

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]
[12. 13. 14. 15.]
[16. 17. 18. 19.]


In [43]:
arr[0,0]

0.0

In [45]:
arr[1,1]

5.0

In [46]:
#use slicing in arrays
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [47]:
arr[0,:]

array([0., 1., 2., 3.])

In [48]:
arr[0,1:3]

array([1., 2.])

In [50]:
arr[:,1:3]

array([[ 1.,  2.],
       [ 5.,  6.],
       [ 9., 10.],
       [13., 14.],
       [17., 18.]])

In [52]:
arr[1:4,1:3]

array([[ 5.,  6.],
       [ 9., 10.],
       [13., 14.]])

In [53]:
arr[0,::-1]

array([3., 2., 1., 0.])

In [54]:
arr[::-1,::-1]

array([[19., 18., 17., 16.],
       [15., 14., 13., 12.],
       [11., 10.,  9.,  8.],
       [ 7.,  6.,  5.,  4.],
       [ 3.,  2.,  1.,  0.]])

fancy indexing

In [55]:
arr = np.arange(21,55,3)
arr

array([21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54])

In [56]:
indices = [1,3,4]
arr[indices]

array([24, 30, 33])

In [57]:
indices = np.array([1,3,5,7])
arr[indices]

array([24, 30, 36, 42])

In [59]:
#change the shape of the new array
indices = np.array([[2,4], [11,9]])
indices

array([[ 2,  4],
       [11,  9]])

In [60]:
arr[indices]

array([[27, 33],
       [54, 48]])

In [61]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
row = np.array([2,3,1])
col = np.array([0,2,1])
arr[row,col]

array([10, 17,  6])