In [22]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [2]:
digits = load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [4]:
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target)

In [7]:
knn = KNeighborsClassifier()
knn

KNeighborsClassifier()

In [8]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [9]:
predictions = knn.predict(x_test)

In [10]:
predictions

array([7, 0, 5, 4, 0, 0, 9, 8, 6, 7, 5, 7, 0, 7, 9, 9, 8, 4, 4, 5, 4, 7,
       6, 2, 3, 3, 4, 2, 5, 5, 4, 1, 5, 3, 9, 1, 3, 8, 1, 8, 7, 5, 8, 2,
       5, 6, 8, 6, 9, 4, 1, 8, 1, 7, 6, 6, 8, 2, 7, 9, 1, 8, 3, 0, 5, 0,
       9, 9, 5, 0, 6, 8, 7, 0, 2, 1, 5, 2, 8, 7, 2, 1, 1, 1, 9, 4, 9, 5,
       1, 3, 2, 3, 9, 8, 0, 3, 5, 8, 4, 0, 3, 9, 2, 5, 4, 7, 0, 9, 5, 9,
       3, 1, 4, 9, 8, 9, 2, 6, 4, 2, 3, 3, 5, 4, 5, 5, 3, 2, 6, 4, 6, 4,
       6, 1, 0, 6, 1, 3, 1, 6, 9, 4, 5, 4, 9, 0, 1, 1, 3, 2, 4, 1, 2, 7,
       5, 1, 1, 1, 3, 2, 4, 8, 1, 1, 5, 6, 5, 9, 9, 1, 8, 9, 7, 2, 5, 4,
       9, 5, 9, 1, 4, 8, 0, 8, 6, 2, 4, 9, 6, 7, 3, 1, 9, 1, 7, 7, 0, 8,
       3, 5, 5, 6, 6, 0, 8, 4, 6, 6, 3, 1, 1, 4, 2, 3, 9, 2, 2, 8, 8, 6,
       2, 8, 2, 7, 6, 3, 5, 0, 7, 0, 3, 4, 2, 7, 1, 6, 1, 1, 9, 3, 7, 3,
       9, 5, 1, 0, 7, 8, 2, 4, 4, 5, 1, 1, 7, 5, 5, 5, 5, 1, 0, 0, 6, 0,
       3, 8, 6, 3, 8, 7, 1, 8, 6, 2, 8, 1, 5, 0, 8, 6, 0, 4, 7, 4, 6, 0,
       2, 4, 1, 5, 6, 7, 5, 1, 1, 4, 3, 9, 9, 9, 2,

In [11]:
# how acurate the algorithm is is calculate by comparing the predictions versus the actual data that we left out

In [12]:
acuracy = knn.score(x_test, y_test)

In [13]:
acuracy

0.9866666666666667

In [17]:
#confusion Matrix
confusion = confusion_matrix(y_test, predictions)
confusion

array([[40,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 57,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 42,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 42,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 50,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0, 49,  1,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0, 43,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 39,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0, 39,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  1, 43]], dtype=int64)

In [19]:
# classification report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.98      1.00      0.99        57
           2       1.00      1.00      1.00        42
           3       0.98      1.00      0.99        42
           4       1.00      0.98      0.99        51
           5       1.00      0.96      0.98        51
           6       0.98      1.00      0.99        43
           7       0.97      1.00      0.99        39
           8       0.97      0.97      0.97        40
           9       0.98      0.96      0.97        45

    accuracy                           0.99       450
   macro avg       0.99      0.99      0.99       450
weighted avg       0.99      0.99      0.99       450



### K-fold Cross-Validation
- we decide how many folds we want to divide the data into, such as k = 10
- first we train with folds 1-9 and test with the 10th fold
- then we train with folds 1-8 and fold 10 and test with the 9th fold
- next we train with folds 1-7 and 9-10 and the use the 8th fold to test
- we repeat this process for all of the folds


In [23]:
kfold = KFold(n_splits = 10, random_state = 11, shuffle = True)

In [24]:
kfold

KFold(n_splits=10, random_state=11, shuffle=True)

In [28]:
score = cross_val_score(estimator = KNeighborsClassifier(), X = digits.data, y = digits.target, cv = kfold)
score

array([0.97777778, 0.99444444, 0.98888889, 0.97777778, 0.98888889,
       0.99444444, 0.97777778, 0.98882682, 1.        , 0.98324022])

In [30]:
score.mean()

0.9872067039106145

### KNN Hyperparameter Tuning
in KNN k: the number of neighbors is a hyperparameter

In [32]:
for k in range(1,20,2):
    kFold = KFold(n_splits = 10, random_state = 11, shuffle = True)
    kNN = KNeighborsClassifier(n_neighbors = k)
    scores = cross_val_score(estimator = kNN, X = digits.data, y = digits.target, cv = kFold)
    print("Neighbors number" ,k,"mean accuracy: ", scores.mean(), "Standard Deviation: ", scores.std())

Neighbors number 1 mean accuracy:  0.9883178150217257 Standard Deviation:  0.005795763429443149
Neighbors number 3 mean accuracy:  0.9883178150217257 Standard Deviation:  0.007228258303699821
Neighbors number 5 mean accuracy:  0.9872067039106145 Standard Deviation:  0.007477762811951388
Neighbors number 7 mean accuracy:  0.9844258224705152 Standard Deviation:  0.009563992727700374
Neighbors number 9 mean accuracy:  0.9838733705772812 Standard Deviation:  0.008028415570318158
Neighbors number 11 mean accuracy:  0.9833178150217255 Standard Deviation:  0.008954270195946442
Neighbors number 13 mean accuracy:  0.9788609559279952 Standard Deviation:  0.008902247681051636
Neighbors number 15 mean accuracy:  0.9788578522656735 Standard Deviation:  0.01019720807761034
Neighbors number 17 mean accuracy:  0.9749689633767845 Standard Deviation:  0.010017314754530991
Neighbors number 19 mean accuracy:  0.9766387337057727 Standard Deviation:  0.009564075820186342
